apiVersion: v1
kind: Service
metadata:
  name: birthday-reminder-service
spec:
  type: LoadBalancer
  selector:
    app: birthday-reminder
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
